# ProjetoIntegrador4-Backend
Backend (Python &amp; Django) do projeto integrador 4 - Senai

Há um conflito em usar o AllAuth e o Djongo (Lib usada para conectar o MangoDB Cloud ao Django), no qual o AllAuth envia um boolean para o Djongo, porem ele não reconhece e sempre retorna erro ao logar.

Aqui esta uma solução para a situação.

https://github.com/doableware/djongo/issues/608#issuecomment-1130292782
